version: '3'
services:
    frontend:
        build: frontend
        ports:
            - 443:443/tcp
            - 80:80/tcp
        environment:
            - CERTBOT_EMAIL=sabae@uw.edu
        depends_on:
            - httpbin
    httpbin:
        image: kennethreitz/httpbin
        expose:
            - 80

