version: '3'
services:
    nginx:
        image: nginx
        ports:
            - 80:80/tcp
        depends_on:
            - httpbin
        volumes: 
            - ./nginx:/etc/nginx/conf.d/
    httpbin:
        image: kennethreitz/httpbin
        expose:
            - 80

